CREATE OR REPLACE DATABASE MYDB;

CREATE OR REPLACE SCHEMA MYDB.MYSCHEMA;

CREATE OR REPLACE TABLE PERMANENT_TABLE (
    ID INT,
    NAME STRING
);

ALTER TABLE PERMANENT_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 3;t

CREATE OR REPLACE TRANSIENT TABLE TRANSIENT_TABLE (
    ID INT,
    NAME STRING
);

CREATE OR REPLACE TEMPORARY TABLE TEMPORARY_TABLE (
    ID INT,
    NAME STRING
);


SHOW TABLES;

